name: Run RSFC analysis

on:
  push:

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run local action
        uses: ./
        with:
          repo_url: https://github.com/${{ github.repository }}
          is_fork: "false"
          pr_sha: ${{ github.sha }}